### ISSUE TITLE
logprot.toml config either does not work or has no effect

### ISSUE THREAD

**Issue by Cleista** [EnigmaticaModpacks/Enigmatica6#4822]
### Modpack Version

Enigmatica 6 1.2.1

### Describe your issue.

I set `logprot.toml` to the following:

```toml
[Login-settings]
	#Time in ticks the logging player is invulnerable, 20 ticks = 1sec. Default is 50secs = 1000 ticks
	#Range: 0 ~ 50000
	invulnerabilityTime = 12000
	#Max distance in blocks(2d) the invulnerability lasts, default: 10
	#Range: 1 ~ 200
	maxDistance = 2

[debug]
	#Wether to enable debug log outputs, default: false
	debugLog = false
```

However, users continue to die while loading, sometimes immediately upon login. This is far less than the 10 minutes of invulnerability expected. 

logprot is in fact loaded as the following is visible in latest.log
```
[11May2022 21:21:19.121] [modloading-worker-23/INFO] [com.logprot.Logprot/]: Shields up!
```

Relevant section of log during player death, occurring ~40 seconds after initial connect:
```log
[11May2022 21:39:08.707] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: TTomoego joined the game
[11May2022 21:39:08.766] [Server thread/INFO] [KubeJS Server/]: server_scripts:enigmatica/kubejs/packmode.js:4: setting mode for player: TTomoego
[11May2022 21:39:08.766] [Server thread/INFO] [KubeJS Server/]: server_scripts:enigmatica/kubejs/packmode.js:7: set mode to expert for player: TTomoego
[11May2022 21:39:08.767] [Server thread/INFO] [se.mickelus.tetra.data.DataManager/]: Sending data to client: TTomoego
[11May2022 21:39:09.405] [Netty Epoll Server IO #21/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize dev.maxneedssnacks.interactio.command.RegistryArgument@2c0861d0 (class dev.maxneedssnacks.interactio.command.RegistryArgument) - will not be sent to client!
[11May2022 21:39:09.989] [Netty Epoll Server IO #21/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize dev.maxneedssnacks.interactio.command.RegistryArgument@2c0861d0 (class dev.maxneedssnacks.interactio.command.RegistryArgument) - will not be sent to client!
[11May2022 21:39:10.929] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: <Xyphyria> o/
[11May2022 21:39:51.061] [Server thread/INFO] [dev.quarris.enigmaticgraves.EnigmaticGraves/]: Preparing grave for TTomoego
[11May2022 21:39:51.061] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: TTomoego was slain by Zombie
[11May2022 21:39:51.063] [Server thread/INFO] [dev.quarris.enigmaticgraves.EnigmaticGraves/]: Spawned grave for TTomoego at BlockPos{x=305, y=79, z=13}
[11May2022 21:39:51.063] [Server thread/INFO] [dev.quarris.enigmaticgraves.EnigmaticGraves/]: Added grave entry to player TTomoego
[11May2022 21:39:53.944] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: <Xyphyria> F
[11May2022 21:40:04.385] [JDA MainWS-ReadThread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: <Tomoego> bruh im in loading
```

Additional context on the Enigmatica Discord [here](https://discord.com/channels/195234321836146688/544822403230859283/974063049612877834).

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server
